### ISSUE TITLE
Dummy Variables

### ISSUE THREAD

**Issue by philipdbest** [sixth-cohort-awesome/nightfour#1]
Submit dummy variables for these -- text file will do.

CKD 1

- Sodium: 1500 milligrams (mg) per day
- Protein 0.8 g/kg body weight per day
- Phosphorus: 1.7 g/day
- Potassium: > 4 g/day
- Total Fat: < 30% of total daily calories
- Cholesterol: < 200 mg/day
- Carbohydrates: 50% of total daily calories

CKD 3

- Sodium: 1500 milligrams (mg) per day
- Protein 0.6 g/kg body weight per day
- Phosphorus: 0.8 g/day
- Potassium:  2 g/day
- Total Fat: < 30% of total daily calories
- Cholesterol: < 200 mg/day
- Carbohydrates: 50% of total daily calories

**Comment by msmorey** [comment]
Sodium: [Bin 1 <1200, Bin 2 (>1200 AND <1500), Bin 3 >1500)

*ADD* Weight: in kg

Dummy Protein: [Bin 1 between 0 and 20g, Bin 2 between 20 and 40g, bin 3 between 40 and 60g, bin 4 between 60 and 80g, bin 5 > 80g]

*CALCULATE* Protein: (median of dummy protein bin)/weight.

Phosphorus: [Bin 1 < 0.5g, Bin 2 <0.6g, Bin 3 < 0.7g, Bin 4 < 0.8g, Bin 5 < 0.9g, Bin 6 < 1 g, Bin 7 >= 1g)

Potassium: [Bin 1 < 2g, Bin 2 between 2 and 4g, Bin 3 > 4g)

Total Fat: > 30% total daily calories? [0/1]

Cholesterol: > 200 mg/day? [0/1]

Carbohydrates: > 50% total daily calories? [0/1]

**Comment by balodge61** [comment]
Sodium: IF 'Na' > 1500, 0 	IF 'Na' <= 1500, 1
Protein: IF 'Pro' <= 0, "NA",	IF 'Pro' > 0 AND <=.4, 4	IF 'Pro' > .4 AND <=.6, 3	IF 'Pro' > .6 AND <=.8, 2	IF 'Pro' > .8, 1  
Phosphorus:IF 'P' <= 0, "NA",	IF 'P' > 0 AND <= .8, 4		IF 'P' > .8 AND <= 1.6, 3	IF 'P' > 1.6 AND <= 2.4, 2	IF 'P' > 2.4, 1 
Potassium: IF 'K' <= 0, "NA",	IF 'K' > 0 AND <= 1, 4		IF 'K' > 1 AND <= 2.5, 3	IF 'K' > 2.5 AND <= 4, 2	IF 'K' > 4, 1
Total Fat: < 30% of total daily calories	IF 'Fat' > .3*'Cal', 1	IF 'Fat' <= .3*'Cal', 0
Cholesterol: < 200 mg/day			IF 'Chol' >= 200, 1	IF 'Chol' < 200, 0
Carbohydrates: 50% of total daily calories	IF 'Carb' > .5*'Cal', 1	IF 'Carb' <= .5*'Cal', 0

**Comment by pballard14** [comment]
maxsod(0,1) is 1500 or not 1500
prot(A,B ...) Bin A for <.4 B between .4 and .8 etc
phosp(A,B ...) Bin A for <.5 B between .5,1 C between 1,1.5 etc
pot(A,B,C,D,E) Bin A for <1 B between 1,2 C between 2,3 D > 3,4 and E >4
totfat(0,1) is <30% or isnt
chol(0,1) is <200 or isnt
carbs(0,1) is 50% or isnt

**Comment by alyssagrubbs** [comment]
Sodium: Binary
- < 1500 mg per day = 0
- > 1500 mg per day = 1
Protein: Bins
- Bin 1: 0 - 0.2 g/kg 
- Bin 2: 0.21 - 0.4 g/kg
- Bin 3: 0.41 - 0.6 g/kg
- Bin 4: 0.61 - 0.8 g/kg
- Bin 5: 0.81 - 1.0 g/kg
- Bin 6: greater than 1 g/kg
Phosphorus: Bins
- Bin 1: 0 - 0.3 g per day
- Bin 2: 0.31 - 0.6 g per day
- Bin 3: 0.61 - 0.9 g per day
- Bin 4: 0.91 - 1.2 g per day
- Bin 5: 1.21 - 1.5 g per day
- Bin 6 1.51 - 1.8 g per day
- Bin 7 > 1.8 g per day
Potassium: Bins
- Bin 1: 0 - 1 g per day
- Bin 2: 1.01 - 2 g per day
- Bin 3: 2.01 - 3 g per day
- Bin 4: 3.01 - 4 g per day
- Bin 5 greater than 4 g per day
Total Fat: Binary
- < 30% of calories = 0
- > 30% of calories = 1
Cholesterol: Binary
- < 200 mg per day = 0
- > 200 mg per day = 1
Carbs: Binary
- < 50 % of calories
- > 50 % of calories

**Comment by PaulNotTaken** [comment]
Sodium: sodium_mg_max_1500 (Y/N - binary)
Protien: protein_g_day_per_kg (.8, .7, .6, .5 - bins)
Phosphorus: phosphorus_1_7_g_per_day (Y/N - binary)
Potassium: potassium_g_per_day (1,2,3,4 - bins)
Total Fat: total_fat_percent_per_day (10,20,30,.... bins)
Cholesterol: total_cholesterol_mg_per_day_max_200 (Y/N - binary)
Carbohydrates: percent_of_total_calories (10, 20, 30,.... bins)

**Comment by tadtenacious** [comment]
True values = 1, False values = 0

'Sodium < 1500mg/day', 
'Protein < .6g/kg/day', 
'Protein > .8g/kg/day', 
'Phosphorus > 1.7g/day', 
'Phosphorus < 0.8g/day', 
'Potassium <= 2g/day',
'Potassium > 4g /day',
'Fat < 30% total cal/day',
'Cholesterol < 200mg/day', 
'Carbs >= 50% total cal/day'

**Comment by jmpugh22** [comment]
•	SODIUM: [IF Bin 1 <1200, IF Bin 2 (>1200 AND <1500), IF Bin 3 >1500)
•	Weight Calculated in: kg
•	PROTIEN: [IF Bin 1 between 0 and 20g, IF Bin 2 between 20 and 40g, IF Bin 3 between 40 and 60g, IF Bin 4 between 60 and 80g, IF Bin 5 > 80g]
•	CALCULATE PROTEIN: (median of protein bin)/weight.
•	PHOSPHORUS: [IF Bin 1 < 0.5g, IF Bin 2 <0.6g, IF Bin 3 < 0.7g, IF Bin 4 < 0.8g, IF Bin 5 < 0.9g, IF Bin 6 < 1 g, IF Bin 7 >= 1g)
•	POTASSIUM: [IF Bin 1 < 2g, IF Bin 2 between 2 and 4g, IF Bin 3 > 4g)
•	TOTAL FAT: > 30% total of daily calories? [0/1]
•	CHOLESTEROL: > 200 mg/day? [0/1]
•	CARBOHYDRATES: > 50% total of daily calories? [0/1]

**Comment by mshi18** [comment]
Sodium: 1500 milligrams (mg) per day   (if it<1000: bin1; if it >1000 but< 1500:bin 2; if  it >1500:bin3)
Protein 0.8 g/kg body weight per day     (if it<0.4:0 bin1; if it >0.4 but< 0.8: bin 2; if  it >0.8:bin3)
Phosphorus: 1.7 g/day  (if it<1.0 bin1; if it >1.0 but< 1.7:bin 2; if  it >1.7: bin3)
Potassium: > 4 g/day(if it<=4: 0; if it >= 4:1)
Total Fat: < 30% of total daily calories(if it<=30%:0; if it >= 30%:1)
Cholesterol: < 200 mg/day(if it<=200:0; if it >= 200:1)
Carbohydrates: 50% of total daily calories(if it<=50%:0; if it > 50%:1)

**Comment by bmalak98** [comment]
Higher Score, Worse Condition (Additive for each measure)

-Sodium:
<800 mg per day LOW || 800-1200 mg per day NORMAL || 1200-1500 mg per day BORDERLINE || 1500 mg per day DANGER ==> (-.25,0,.5,1)

Protein: 
>1.2 CHECK || .8 - 1 NORMAL || .6-.8 BAD || <.6 DANGER ==>  (.25,0,.5,1)

Phosphorus: 
>1.7 g/day GOOD  || 1.2 - 1 CAUTION  ||  1 - 1.2  TAKE IMMED ACTION || < .8 DANGER  ==> (0,.5, 1, 2)

Potassium:  
<2 g/day WARNING || 2- 4 g/day CAUTION ||  >4 g/day OK ==> (0,1)

Total Fat: 
10-30%  MAINTAIN || > 30%  REDUCE ==> (0,1)

Cholesterol:  
< 200 mg/day GOOD || >= 200 mg/day BAD ==> (0,1)

Carbohydrates: 
25-40% GOOD ||40-50% TRENDING HIGH || >50% WARNING ==> (0,.5,1)

**Comment by Sronan010** [comment]
![image](https://user-images.githubusercontent.com/36869131/37188579-87a65280-2315-11e8-9bdc-6bc7df79520a.png)
